server:
  port: 8001
  servlet:
    context-path: /share-prepose-web


spring:
  datasource:
#    jndi-name: ds-sstax_jxjy
    driver-class-name: oracle.jdbc.OracleDriver
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      url: jdbc:oracle:thin:@10.204.0.249:1521:orcl
      username: jxjy_qzj
      password: oracle
      initial-size: 10
      min-idle: 5
      max-active: 50
      max-wait: 60000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 1 FROM DUAL
      test-while-idle: true
      test-on-borrow: true
      test-on-return: false
      remove-abandoned: true
      remove-abandoned-timeout: 1800

cxf:
  path: /webservice
mybatis-plus:
  config-location: classpath:META-INF/config/mybatis-config.xml
  type-aliases-package: com.tzsw.model
  mapper-locations: classpath:META-INF/config/mappers/**/*.xml



